# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160602_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Описание'),
        ),
    ]
