# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_test_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
