# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160604_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', verbose_name='Описание вопроса'),
        ),
    ]
