# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_answer_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст варианта')),
                ('points', models.IntegerField(verbose_name='Количество баллов')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_variant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.AnswerVariant', verbose_name='Вариант ответа'),
            preserve_default=False,
        ),
    ]
